//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Globla_Movies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actor
    {
        public int act_id { get; set; }
        public string act_fname { get; set; }
        public string act_lname { get; set; }
        public string act_gender { get; set; }
    
        public virtual Movie_Cast Movie_Cast { get; set; }
    }
}
