//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Globla_Movies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie_Cast
    {
        public int act_id { get; set; }
        public Nullable<int> mov_id { get; set; }
        public string role { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
