//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Globla_Movies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie()
        {
            this.Movie_Cast = new HashSet<Movie_Cast>();
        }
    
        public int mov_id { get; set; }
        public string mov_title { get; set; }
        public Nullable<int> mov_year { get; set; }
        public Nullable<System.TimeSpan> mov_time_ { get; set; }
        public string mov_lang { get; set; }
        public Nullable<System.DateTime> mov_dt_rel { get; set; }
        public string mov_rel_country_ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movie_Cast> Movie_Cast { get; set; }
        public virtual Movie_Dir Movie_Dir { get; set; }
        public virtual Movie_Genre Movie_Genre { get; set; }
        public virtual rating rating { get; set; }
    }
}
